---
# role: ansible-role-tftpd
# file: tasks/tasks.yml

- name: "Install packages for tftpd-hpa"
  package:
    name: "{{ tftpd_packages }}"
    state: present

- name: "Ensure tftp root is present"
  file:
    path: "{{ tftpd_root }}"
    owner: "{{ tftpd_root_owner }}"
    group: "{{ tftpd_root_group }}"
    mode: "{{ tftpd_root_mode }}"
    state: directory

- name: "Configure tftpd"
  template:
    src: "{{ ansible_os_family }}/tftpd.j2"
    dest: "{{ tftpd_conf_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart and enable tftpd

- name: "Set SElinux context for tftpd root"
  sefcontext:
    target: '{{ tftp_root }}(/.*)?'
    setype: '{{ tftp_setype }}'
    state: present
  when: ansible_selinux is defined
    and ansible_selinux | bool
    and ansible_selinux.status == 'enabled'
