---
# role: ansible-role-tftpd
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: alpine-tftpd
    image: "jam82/molecule-alpine:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: arch-tftpd
    image: "jam82/molecule-archlinux:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: centos-tftpd
    image: "jam82/molecule-centos:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: debian-tftpd
    image: "jam82/molecule-debian:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: fedora-tftpd
    image: "jam82/molecule-fedora:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: opensuse-tftpd
    image: "jam82/molecule-opensuse:15"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: tumbleweed-tftpd
    image: "jam82/molecule-opensuse:tumbleweed"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: oracle-tftpd
    image: "jam82/molecule-oraclelinux:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: ubuntu-tftpd
    image: "jam82/molecule-ubuntu:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        tftpd_role_enabled: true
        tftpd_root: /srv/tftp
verifier:
  name: ansible
